# CDS303 Session 1 : Data Collection & Paper Understanding

## Setup

In [1]:
# data pre-processing
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler

# data mining
from sklearn.decomposition import PCA

# visualization
import matplotlib.pyplot as plt
import matplotlib
import seaborn as sns

import warnings
warnings.filterwarnings(action = 'ignore')

## 1. Loading the dataset

In [12]:
file_name = 'stock portfolio performance data set.xlsx'
stock = pd.read_excel(file_name,
                      index_col=0,               # having the first column as an index
                      skiprows=1,                # skips the first row of the file 
                      sheet_name='all period')   # selects the exact sheet number
                                                                                
stock.head()

,Large B/P,Large ROE,Large S/P,Large Return Rate in the last quarter,Large Market Value,Small systematic Risk,Annual Return,Excess Return,Systematic Risk,Total Risk,Abs. Win Rate,Rel. Win Rate,Annual Return.1,Excess Return.1,Systematic Risk.1,Total Risk.1,Abs. Win Rate.1,Rel. Win Rate.1
ID,,,,,,,,,,,,,,,,,,
1,1.0,0.0,0.0,0.0,0.0,0.0,0.139,0.010,1.33,0.149,0.663,0.525,0.531875,0.478116,0.738015,0.800000,0.52,0.411765
2,0.0,1.0,0.0,0.0,0.0,0.0,0.143,0.010,1.17,0.108,0.663,0.650,0.549712,0.487595,0.571579,0.412231,0.52,0.764706
3,0.0,0.0,1.0,0.0,0.0,0.0,0.173,0.018,1.30,0.144,0.638,0.513,0.692625,0.629895,0.703051,0.756879,0.44,0.376471
4,0.0,0.0,0.0,1.0,0.0,0.0,0.096,-0.002,1.39,0.144,0.613,0.475,0.324351,0.255634,0.800000,0.756046,0.36,0.270588
5,0.0,0.0,0.0,0.0,1.0,0.0,0.096,0.001,1.04,0.087,0.725,0.538,0.326615,0.306501,0.432452,0.209289,0.72,0.447059

## 2. Checking the missing value

In [13]:
stock.isnull().sum()

 Large B/P                                 0
 Large ROE                                 0
 Large S/P                                 0
 Large Return Rate in the last quarter     0
 Large Market Value                        0
 Small systematic Risk                     0
Annual Return                              0
Excess Return                              0
Systematic Risk                            0
Total Risk                                 0
Abs. Win Rate                              0
Rel. Win Rate                              0
Annual Return.1                            0
Excess Return.1                            0
Systematic Risk.1                          0
Total Risk.1                               0
Abs. Win Rate.1                            0
Rel. Win Rate.1                            0
dtype: int64

## 3. Checking the variable types

In [15]:
stock.info()

<class 'pandas.core.frame.DataFrame'>
Index: 63 entries, 1 to 63
Data columns (total 18 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0    Large B/P                               63 non-null     float64
 1    Large ROE                               63 non-null     float64
 2    Large S/P                               63 non-null     float64
 3    Large Return Rate in the last quarter   63 non-null     float64
 4    Large Market Value                      63 non-null     float64
 5    Small systematic Risk                   63 non-null     float64
 6   Annual Return                            63 non-null     float64
 7   Excess Return                            63 non-null     float64
 8   Systematic Risk                          63 non-null     float64
 9   Total Risk                               63 non-null     float64
 10  Abs. Win Rate                            63 non-null     float64
 11  Rel. Win Rate                            63 non-null     float64
 12  Annual Return.1                          63 non-null     float64
 13  Excess Return.1                          63 non-null     float64
 14  Systematic Risk.1                        63 non-null     float64
 15  Total Risk.1                             63 non-null     float64
 16  Abs. Win Rate.1                          63 non-null     float64
 17  Rel. Win Rate.1                          63 non-null     float64
dtypes: float64(18)
memory usage: 9.4 KB

## 4. Checking the basic statistics

In [16]:
stock.describe()

,Large B/P,Large ROE,Large S/P,Large Return Rate in the last quarter,Large Market Value,Small systematic Risk,Annual Return,Excess Return,Systematic Risk,Total Risk,Abs. Win Rate,Rel. Win Rate,Annual Return.1,Excess Return.1,Systematic Risk.1,Total Risk.1,Abs. Win Rate.1,Rel. Win Rate.1
count,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000
mean,0.166619,0.166619,0.166619,0.166619,0.166619,0.166619,0.149238,0.014746,1.035873,0.106317,0.677397,0.573460,0.580151,0.576170,0.426494,0.391749,0.566984,0.547899
std,0.199304,0.199304,0.199304,0.199304,0.199304,0.199304,0.027872,0.007101,0.112173,0.014277,0.035196,0.056496,0.133358,0.137047,0.118178,0.136653,0.112803,0.159468
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.070000,-0.005000,0.820000,0.086000,0.563000,0.450000,0.200000,0.200000,0.200000,0.200000,0.200000,0.200000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.138000,0.012000,0.970000,0.096500,0.663000,0.525000,0.525811,0.519093,0.358600,0.297324,0.520000,0.411765
50%,0.167000,0.167000,0.167000,0.167000,0.167000,0.167000,0.153000,0.015000,1.010000,0.104000,0.675000,0.575000,0.598516,0.587148,0.403418,0.368958,0.560000,0.552941
75%,0.291500,0.291500,0.291500,0.291500,0.291500,0.291500,0.170000,0.019500,1.080000,0.113000,0.700000,0.625000,0.679636,0.669294,0.470571,0.457749,0.640000,0.694118
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.195000,0.026000,1.390000,0.149000,0.750000,0.663000,0.800000,0.800000,0.800000,0.800000,0.800000,0.800000